---
version: "3.6"
volumes:
  shared-workspace:
    name: "hadoop-distributed-file-system"
    driver: local
services:
  jupyterlab:
    build: ./build/pyspark-notebook
    container_name: jupyterlab
    command: ["jupyter", "lab", "--no-browser", "--NotebookApp.token="]
    ports:
      - 8888:8888
      - 4040:4040
    volumes:
      - shared-workspace:/opt/workspace
  spark-master:
    build: ./build/pyspark-notebook
    container_name: spark-master
    user: root
    environment:
      - SPARK_NO_DAEMONIZE=true
    entrypoint: /usr/local/spark/sbin/start-master.sh
    ports:
      - 8080:8080
      - 7077:7077
    volumes:
      - shared-workspace:/opt/workspace
  spark-worker-1:
    build: ./build/pyspark-notebook
    container_name: spark-worker-1
    environment:
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=6144m
      - SPARK_NO_DAEMONIZE=true
    user: root
    entrypoint: /usr/local/spark/sbin/start-worker.sh spark://spark-master:7077
    ports:
      - 8081:8081
    volumes:
      - shared-workspace:/opt/workspace
    depends_on:
      - spark-master
#   spark-worker-2:
#     image: w3s/spark-worker:3.2.1
#     container_name: spark-worker-2
#     environment:
#       - SPARK_WORKER_CORES=2
#       - SPARK_WORKER_MEMORY=6144m
#     ports:
#       - 8082:8081
#     volumes:
#       - shared-workspace:/opt/workspace
#     depends_on:
#       - spark-master
#   spark-worker-3:
#     image: w3s/spark-worker:3.2.1
#     container_name: spark-worker-3
#     environment:
#       - SPARK_WORKER_CORES=2
#       - SPARK_WORKER_MEMORY=6144m
#     ports:
#       - 8083:8081
#     volumes:
#       - shared-workspace:/opt/workspace
#     depends_on:
#       - spark-master
#   spark-worker-4:
#     image: w3s/spark-worker:3.2.1
#     container_name: spark-worker-4
#     environment:
#       - SPARK_WORKER_CORES=2
#       - SPARK_WORKER_MEMORY=6144m
#     ports:
#       - 8084:8081
#     volumes:
#       - shared-workspace:/opt/workspace
#     depends_on:
#       - spark-master
# ...